### ISSUE TITLE
Getting Sprockets::FileNotFound error

### ISSUE THREAD

**Issue by wemmick** [seankay/readmorejs-rails#2]
I followed your instructions on how to install the game, but I get this error:

`couldn't find file 'readmore.js' with type 'application/javascript'` within app/views/layouts/application.html.erb

Any ideas?  Happy to provide whatever file snippets are helpful.

**Comment by lelbarton** [comment]
Meaning no offence, but did you remember to restart your server after installing the gem?

**Comment by joeldowns** [comment]
I don't remember exactly how I resolved this (it's been a while), but I did, so we can close this.  Thanks!

**Comment by seankay** [comment]
Thanks for letting me know guys. Sorry I didn't get back to you in time!
